version: '2.1'
services:
  app:
    image: arpitjindal1997/myst-multiarch:wireguard
    cap_add:
     - NET_ADMIN
     - SYS_MODULE
    sysctls:
     - net.ipv6.conf.all.disable_ipv6=0
     - net.ipv6.conf.all.forwarding=1
    environment:
     - WG_COLOR_MODE=always
     - LOG_LEVEL=info
    ports:
     - 51820:51820/udp
    networks:
      app_net:
        ipv6_address: 2001:3200:3200::20
networks:
  app_net:
    enable_ipv6: true
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 2001:3200:3200::/64
          gateway: 2001:3200:3200::1
